export const tabelaDeValores = new Map(Object.entries({
    "Material de Base 1": {
        "%C": 0,
        "%Si": 0,
        "%Mn": 0,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%P": 0,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "Material de Análise": {
        "%C": 0,
        "%Si": 0,
        "%Mn": 0,
        "%Cr": 0,
        "%Mo": 0,
        "%Cu": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%P": 0,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "Material de Base 2": {
        "%C": 0,
        "%Si": 0,
        "%Mn": 0,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%P": 0,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "Material de Adição": {
        "%C": 0,
        "%Si": 0,
        "%Mn": 0,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%P": 0,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "ASTM A-36": {
        "%C": 0.26,
        "%Si": 0.275,
        "%Mn": 1,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1020": {
        "%C": 0.205,
        "%Si": 0.25,
        "%Mn": 0.45,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1030": {
        "%C": 0.31,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1040": {
        "%C": 0.405,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1050": {
        "%C": 0.515,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1060": {
        "%C": 0.6,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1070": {
        "%C": 0.7,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1080": {
        "%C": 0.815,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 1090": {
        "%C": 0.915,
        "%Si": 0.25,
        "%Mn": 0.75,
        "%Cr": 0,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.05,
        "%P": 0.04,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 4120": {
        "%C": 0.205,
        "%Si": 0.25,
        "%Mn": 1.05,
        "%Cr": 0.5,
        "%Cu": 0,
        "%Mo": 0.165,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.04,
        "%P": 0.035,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 4130": {
        "%C": 0.305,
        "%Si": 0.25,
        "%Mn": 0.5,
        "%Cr": 0.95,
        "%Cu": 0,
        "%Mo": 0.2,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.04,
        "%P": 0.035,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 4140": {
        "%C": 0.405,
        "%Si": 0.25,
        "%Mn": 0.875,
        "%Cr": 0.95,
        "%Cu": 0,
        "%Mo": 0.2,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.04,
        "%P": 0.035,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "SAE 4150": {
        "%C": 0.505,
        "%Si": 0.25,
        "%Mn": 0.875,
        "%Cr": 0.95,
        "%Cu": 0,
        "%Mo": 0.2,
        "%Ni": 0,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.04,
        "%P": 0.035,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER70S-A1": {
        "%C": 0.12,
        "%Si": 0.5,
        "%Mn": 1.3,
        "%Cr": 0,
        "%Cu": 0.35,
        "%Mo": 0.525,
        "%Ni": 0.2,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER80S-B2": {
        "%C": 0.095,
        "%Si": 0.55,
        "%Mn": 0.55,
        "%Cr": 1.35,
        "%Cu": 0.35,
        "%Mo": 0.525,
        "%Ni": 0.2,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER70S-B2L": {
        "%C": 0.05,
        "%Si": 0.55,
        "%Mn": 0.55,
        "%Cr": 1.35,
        "%Cu": 0.35,
        "%Mo": 0.525,
        "%Ni": 0.2,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER90S-B3": {
        "%C": 0.095,
        "%Si": 0.55,
        "%Mn": 0.55,
        "%Cr": 2.5,
        "%Cu": 0.35,
        "%Mo": 1.05,
        "%Ni": 0.2,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER80S-B3L": {
        "%C": 0.05,
        "%Si": 0.5,
        "%Mn": 0.55,
        "%Cr": 2.5,
        "%Cu": 0.35,
        "%Mo": 1.05,
        "%Ni": 0.6,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER80S-B6": {
        "%C": 0.1,
        "%Si": 0.5,
        "%Mn": 0.55,
        "%Cr": 5.25,
        "%Cu": 0.35,
        "%Mo": 0.55,
        "%Ni": 0.6,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },

    "AWS ER80S-B8": {
        "%C": 0.1,
        "%Si": 0.5,
        "%Mn": 0.55,
        "%Cr": 9.25,
        "%Cu": 0.35,
        "%Mo": 1,
        "%Ni": 0.6,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.025,
        "%P": 0.025,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "ABNT 301": {
        "%C": 0.15,
        "%Si": 1,
        "%Mn": 2,
        "%Cr": 17,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 7,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.045,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "ABNT 304": {
        "%C": 0.08,
        "%Si": 1,
        "%Mn": 2,
        "%Cr": 18.75,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 10,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.045,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "ABNT 304L": {
        "%C": 0.03,
        "%Si": 1,
        "%Mn": 2,
        "%Cr": 18.75,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 13.5,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.045,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0

    },
    "AISI 308": {
        "%C": 0.08,
        "%Si": 0.475,
        "%Mn": 1.75,
        "%Cr": 20.75,
        "%Cu": 0.75,
        "%Mo": 0.75,
        "%Ni": 10,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "ABNT 309": {
        "%C": 0.2,
        "%Si": 1,
        "%Mn": 2,
        "%Cr": 23,
        "%Cu": 0,
        "%Mo": 0,
        "%Ni": 13.5,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "AWS 308": {
        "%C": 0.08,
        "%Si": 0.475,
        "%Mn": 1.75,
        "%Cr": 20.75,
        "%Cu": 0.75,
        "%Mo": 0.75,
        "%Ni": 10,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0

    },
    "AWS 309": {
        "%C": 0.12,
        "%Si": 0.475,
        "%Mn": 1.75,
        "%Cr": 24,
        "%Cu": 0.75,
        "%Mo": 0.75,
        "%Ni": 13,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "AWS 310": {
        "%C": 0.115,
        "%Si": 0.475,
        "%Mn": 1.75,
        "%Cr": 26.5,
        "%Cu": 0.75,
        "%Mo": 0.75,
        "%Ni": 21.25,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    },
    "AWS 316": {
        "%C": 0.08,
        "%Si": 0.475,
        "%Mn": 1.75,
        "%Cr": 19,
        "%Cu": 0.75,
        "%Mo": 2.5,
        "%Ni": 12.5,
        "%Nb": 0,
        "%Ti": 0,
        "%N": 0,
        "%S": 0.03,
        "%P": 0.03,
        "%V": 0,
        "%B": 0,
        "density": 0,
        "cal_esp": 0,
        "therm_diffusivity": 0,
        "therm_conductivity": 0
    }
}))


export const acosC = ["ASTM A-36", "SAE 1020", "SAE 1030", "SAE 1040",
    "SAE 1050", "SAE 1060", "SAE 1070", "SAE 1080",
    "SAE 1090", "SAE 4120", "SAE 4130", "SAE 4140",
    "SAE 4150"]

export const acosInoxBase = ["ABNT 301", "ABNT 304", "ABNT 304L", "ABNT 309"]
export const acosInoxAdicao = ["AWS 308", "AWS 309", "AWS 310", "AWS 316"]
export const acosDeAdicao = ["HELLO WORLD"]
